---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traces
subjects:
  - kind: ServiceAccount
    name: traces
