---
apiVersion: v1
kind: Service
metadata:
  name: traces
spec:
  ports:
    - port: 4317
      targetPort: 4317
      name: otlp
    - port: 4318
      targetPort: 4318
      name: otlphttp
    - port: 55680
      targetPort: 55680
      name: otlplegacy
    - port: 55681
      targetPort: 4318
      name: otlphttplegacy
