---
apiVersion: v1
kind: Service
metadata:
  name: traces
spec:
  ports:
    - port: 4317
      targetPort: 4317
      name: otlp
    - port: 4318
      targetPort: 4318
      name: otlphttp
    - port: 9411
      targetPort: 9411
      name: zipkin
