---
resources:
  - ../../../bases/events/noop
  - constraints.yaml

namespace: observe

namePrefix: observe-openshift-

patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: events
    path: deployment.yaml
  - target:
      version: v1
      group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: events
    path: clusterrole.yaml
