---
bases:
  - ../base
namePrefix: observe-
commonLabels:
  observeinc.com/component: 'traces'
resources:
  - daemonset.yaml
images:
  - name: otel/opentelemetry-collector-contrib
    newTag: '0.88.0'
