---
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - service.yaml

commonLabels:
  observeinc.com/component: 'traces'

configMapGenerator:
  - name: otel-collector-env
    literals:
      - OBSERVE_COLLECTOR_HOST=collect.observeinc.com
      - OBSERVE_COLLECTOR_PORT=443
      - OBSERVE_COLLECTOR_SCHEME=https
      - OBSERVE_COLLECTOR_INSECURE=off
      - OBSERVE_COLLECTOR_OTEL_VERSION=v1
      - OTEL_SENDING_QUEUE=4
      - OTEL_QUEUE_SIZE=100
      - OTEL_RETRY_ON_FAILURE=true
      - OTEL_SAMPLER_HASH_SEED=22
      - OTEL_SAMPLER_PERCENTAGE=100
      - OTEL_MEMORY_LIMITER_LIMIT_PERCENTAGE=80
      - OTEL_MEMORY_LIMITER_SPIKE_LIMIT_PERCENTAGE=25
      - OTEL_MEMORY_LIMITER_CHECK_INTERVAL=5s
      # known to not work: https://github.com/open-telemetry/opentelemetry-collector/issues/4328
      - OTEL_SEND_BATCH_MAX_SIZE=0
      - OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT=1048576
      - OTEL_SERVICE_VERSION_LABEL_KEY_REGEX=(pod-template-hash|controller-revision-hash|job-name)
      # must be modified to `upsert` in order to override default cluster UID
      - OTEL_OBSERVE_CLUSTER_ACTION=insert
  - name: otel-collector
    literals:
      - extra.yaml=
    files:
      - config.yaml
