resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- role.yaml
- rolebinding.yaml
- serviceaccount.yaml

configMapGenerator:
  - name: kube-state-events-env
    literals:
      - V=2
