---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: state
rules:
  - apiGroups: [""]
    verbs: ["list", "get", "watch"]
    resources:
      - "*"
  - apiGroups: ["apps"]
    verbs: ["list", "get", "watch"]
    resources:
      - "*"
  - apiGroups: ["networking.k8s.io"]
    verbs: ["list", "get", "watch"]
    resources:
      - "*"
