---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: events
subjects:
  - kind: ServiceAccount
    name: events
