resources:
  - daemonset.yaml

configMapGenerator:
- name: observe-agent-config
  files:
    - telegraf.conf
    - fluent-bit.conf
    - parsers.conf

images:
- name: observeinc/telegraf
  newTag: '1.17'
- name: fluent/fluent-bit
  newTag: '1.8.7'
