---
resources:
  - daemonset.yaml

configMapGenerator:
  - name: observe-agent-config
    files:
      - telegraf.conf
      - fluent-bit.conf
      - parsers.conf
  - name: fluent-bit-env
    literals:
      - FB_BUFFER_CHUNK_SIZE=32k
      - FB_BUFFER_MAX_SIZE=256k
      - FB_DOCKER_MODE=On
      - FB_DOCKER_MODE_FLUSH=4
      - FB_FLUSH=2
      - FB_GRACE=10
      - FB_MEM_BUF_LIMIT=5MB
      - FB_REFRESH_INTERVAL=2
      - FB_ROTATE_WAIT=5
      - OBSERVE_COLLECTOR_HOST=collect.observeinc.com
      - OBSERVE_COLLECTOR_PORT=443
      - OBSERVE_COLLECTOR_TLS=on

images:
  - name: telegraf
    newTag: '1.20'
  - name: fluent/fluent-bit
    newTag: '1.8.7'
