apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
spec:
  template:
    spec:
      containers:
        - name: grafana-agent
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 4Gi
