apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traces
spec:
  template:
    spec:
      containers:
        - name: otel-collector
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
