---
name: Test apply

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Testing
        run: |
          export KUBECONFIG="$(kind get kubeconfig-path)"
          kubectl cluster-info
