---
name: Test apply

on: pull_request

jobs:
  cluster-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@main
        with:
          kubectl_version: v1.29.0    # leading edge  (EOL 2025-02-28)
          node_image: kindest/node:v1.29.0@sha256:54a50c9354f11ce0aa56a85d2cacb1b950f85eab3fe1caf988826d1f89bf37eb
        env:
          KUBE_CONFIG: .kubeconfig
      - name: Label check
        run: make label_check
      - name: Test apply
        env:
          OBSERVE_CUSTOMER: ${{ secrets.OBSERVE_CUSTOMER }}
          OBSERVE_TOKEN: ${{ secrets.OBSERVE_TOKEN }}
        run: make apply
      - name: Test delete
        run: make delete
