---
name: Test apply

on: pull_request

jobs:
  cluster-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@main
        with:
          kubectl_version: v1.28.3    # leading edge  (EOL 2024-10-28)
          node_image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
        env:
          KUBE_CONFIG: .kubeconfig
      - name: Label check
        run: make label_check
      - name: Test apply
        env:
          OBSERVE_CUSTOMER: ${{ secrets.OBSERVE_CUSTOMER }}
          OBSERVE_TOKEN: ${{ secrets.OBSERVE_TOKEN }}
        run: make apply
      - name: Test delete
        run: make delete
